apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      selector:
        matchLabels:
          app: backend-feed
          tier: backend
      containers:
        - image: patrikb/udacity-restapi-feed
          name: backend-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
